[build]
  base = "Downloads/project-bolt-sb1-cmxywraz (3)/project"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 